spring.application.name=ms-promociones


# Configuración del puerto del servidor
server.port=8083

# Configuración de conexión a la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/db_promociones
spring.datasource.username=root
spring.datasource.password=root

# Configuración de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect